# Generated by Django 5.1.4 on 2024-12-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mercado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
